Repository micronaut-projects/micronaut-sourcegen, pull requests merged in 2024-01, with the labels that each got.

#20 [sourcegen] Update common files for branch master
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: relates-to: build

#25 Add support for generating Javadoc
  sourcegen-generator-java/src/main/java/io/micronaut/sourcegen/JavaPoetSourceGenerator.java
  sourcegen-generator-kotlin/src/main/java/io/micronaut/sourcegen/KotlinPoetSourceGenerator.java
  sourcegen-model/src/main/java/io/micronaut/sourcegen/model/AbstractElement.java
  sourcegen-model/src/main/java/io/micronaut/sourcegen/model/AbstractElementBuilder.java
  sourcegen-model/src/main/java/io/micronaut/sourcegen/model/ClassDef.java
  sourcegen-model/src/main/java/io/micronaut/sourcegen/model/EnumDef.java
  sourcegen-model/src/main/java/io/micronaut/sourcegen/model/FieldDef.java
  sourcegen-model/src/main/java/io/micronaut/sourcegen/model/InterfaceDef.java
  sourcegen-model/src/main/java/io/micronaut/sourcegen/model/MethodDef.java
  sourcegen-model/src/main/java/io/micronaut/sourcegen/model/ParameterDef.java
  sourcegen-model/src/main/java/io/micronaut/sourcegen/model/PropertyDef.java
  sourcegen-model/src/main/java/io/micronaut/sourcegen/model/RecordDef.java
Labels: type: enhancement

#22 [sourcegen] Update common files for branch master
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: relates-to: build

#29 Fix parameter annotations (again)
  sourcegen-generator-java/src/main/java/io/micronaut/sourcegen/JavaPoetSourceGenerator.java
  test-suite-custom-generators/src/main/java/io/micronaut/sourcegen/custom/visitor/GenerateMyBean3Visitor.java
  test-suite-java/src/test/java/io/micronaut/sourcegen/example/MyBean3Test.java
Labels: type: bug

#31 Add test to reference a generated class from generics
  test-suite-java/build.gradle.kts
  test-suite-java/src/main/java/io/micronaut/sourcegen/example/OtherBean.java
  test-suite-java/src/test/java/io/micronaut/sourcegen/example/OtherBeanTest.java
Labels: type: improvement

#30 add support for static methods
  settings.gradle.kts
  sourcegen-generator-java/src/main/java/io/micronaut/sourcegen/JavaPoetSourceGenerator.java
  sourcegen-generator-kotlin/src/main/java/io/micronaut/sourcegen/KotlinPoetSourceGenerator.java
  sourcegen-generator/src/main/java/io/micronaut/sourcegen/generator/SourceGenerators.java
  sourcegen-generator/src/main/java/io/micronaut/sourcegen/generator/visitors/BuilderAnnotationVisitor.java
  sourcegen-model/src/main/java/io/micronaut/sourcegen/model/ExpressionDef.java
  test-suite-custom-generators/src/main/java/io/micronaut/sourcegen/custom/visitor/GenerateMyEnum1.java
  test-suite-custom-generators/src/main/java/io/micronaut/sourcegen/custom/visitor/GenerateMyRecord1Visitor.java
  test-suite-java/src/test/java/io/micronaut/sourcegen/example/MyRecord1Test.java
Labels: type: enhancement

#37 support default values for primtives/strings in @Builder
  sourcegen-generator-java/src/main/java/io/micronaut/sourcegen/JavaPoetSourceGenerator.java
  sourcegen-generator-kotlin/src/main/java/io/micronaut/sourcegen/KotlinPoetSourceGenerator.java
  sourcegen-generator/src/main/java/io/micronaut/sourcegen/generator/visitors/BuilderAnnotationVisitor.java
  sourcegen-model/src/main/java/io/micronaut/sourcegen/model/ExpressionDef.java
  sourcegen-model/src/main/java/io/micronaut/sourcegen/model/FieldDef.java
  test-suite-java/src/main/java/io/micronaut/sourcegen/example/Person2.java
  test-suite-java/src/test/java/io/micronaut/sourcegen/example/PersonBuilderTest.java
Labels: type: enhancement

#35 Generate files in `visitClass`, correct Kotlin
  sourcegen-generator-kotlin/src/main/java/io/micronaut/sourcegen/KotlinPoetSourceGenerator.java
  sourcegen-generator/src/main/java/io/micronaut/sourcegen/generator/visitors/BuilderAnnotationVisitor.java
  test-suite-custom-generators/src/main/java/io/micronaut/sourcegen/custom/visitor/CopyAnnotationsVisitor.java
  test-suite-custom-generators/src/main/java/io/micronaut/sourcegen/custom/visitor/GenerateMyBean1Visitor.java
  test-suite-custom-generators/src/main/java/io/micronaut/sourcegen/custom/visitor/GenerateMyBean2Visitor.java
  test-suite-custom-generators/src/main/java/io/micronaut/sourcegen/custom/visitor/GenerateMyBean3Visitor.java
  test-suite-custom-generators/src/main/java/io/micronaut/sourcegen/custom/visitor/GenerateMyEnum1.java
  test-suite-custom-generators/src/main/java/io/micronaut/sourcegen/custom/visitor/GenerateMyInterface1Visitor.java
  test-suite-custom-generators/src/main/java/io/micronaut/sourcegen/custom/visitor/GenerateMyRecord1Visitor.java
  test-suite-custom-generators/src/main/java/io/micronaut/sourcegen/custom/visitor/GenerateMyRecord2Visitor.java
  test-suite-custom-generators/src/main/java/io/micronaut/sourcegen/custom/visitor/GenerateMyRepository1Visitor.java
Labels: type: improvement

#39 [sourcegen] Update common files for branch master
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
Labels: relates-to: build
