Repository micronaut-projects/micronaut-sourcegen, pull requests merged in 2024-08, with the labels that each got.

#127 [sourcegen] Update common files for branch 1.2.x
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: relates-to: build

#129 fix empty builder generation
  sourcegen-generator/src/main/java/io/micronaut/sourcegen/generator/visitors/BuilderAnnotationVisitor.java
  sourcegen-generator/src/main/java/io/micronaut/sourcegen/generator/visitors/SuperBuilderAnnotationVisitor.java
  sourcegen-generator/src/test/groovy/io/micronaut/sourcegen/generator/visitors/BuilderAnnotationVisitorSpec.groovy
  test-suite-java/src/main/java/io/micronaut/sourcegen/example/EmptyChild.java
  test-suite-java/src/main/java/io/micronaut/sourcegen/example/EmptyParent.java
  test-suite-java/src/main/java/io/micronaut/sourcegen/example/EmptyThing.java
  test-suite-java/src/test/java/io/micronaut/sourcegen/example/EmptyTest.java
Labels: type: bug

#135 Add an ability to introspect builders
  sourcegen-annotations/src/main/java/io/micronaut/sourcegen/annotations/Builder.java
  sourcegen-annotations/src/main/java/io/micronaut/sourcegen/annotations/SuperBuilder.java
  sourcegen-generator/src/main/java/io/micronaut/sourcegen/generator/visitors/BuilderAnnotationVisitor.java
  sourcegen-generator/src/main/java/io/micronaut/sourcegen/generator/visitors/SuperBuilderAnnotationVisitor.java
  sourcegen-generator/src/test/groovy/io/micronaut/sourcegen/generator/visitors/BuilderAnnotationVisitorSpec.groovy
  test-suite-java/src/test/java/io/micronaut/sourcegen/example/AnimalSuperBuilderTest.java
  test-suite-java/src/test/java/io/micronaut/sourcegen/example/PersonBuilderTest.java
Labels: type: improvement
