Repository micronaut-projects/micronaut-sourcegen, pull requests merged in 2025-01, with the labels that each got.

#217 Public class should be generated with a public default constructor
  sourcegen-bytecode-writer/src/main/java/io/micronaut/sourcegen/bytecode/ByteCodeWriter.java
  sourcegen-bytecode-writer/src/test/java/io/micronaut/sourcegen/bytecode/ByteCodeWriterTest.java
Labels: bug

#219 Support accessing array element using an expression
  sourcegen-bytecode-writer/src/main/java/io/micronaut/sourcegen/bytecode/expression/ArrayElementExpressionWriter.java
  sourcegen-bytecode-writer/src/test/java/io/micronaut/sourcegen/bytecode/ByteCodeWriterTest.java
  sourcegen-model/src/main/java/io/micronaut/sourcegen/model/ExpressionDef.java
Labels: type: improvement

#220 Add Java idiom for concatenating strings
  sourcegen-bytecode-writer/src/test/java/io/micronaut/sourcegen/bytecode/ByteCodeWriterTest.java
  sourcegen-generator/src/main/java/io/micronaut/sourcegen/generator/visitors/ObjectAnnotationVisitor.java
  sourcegen-model/src/main/java/io/micronaut/sourcegen/model/JavaIdioms.java
Labels: type: improvement

#222 Add not-equals expressions
  sourcegen-bytecode-writer/src/main/java/io/micronaut/sourcegen/bytecode/AbstractConditionalWriter.java
  sourcegen-bytecode-writer/src/test/java/io/micronaut/sourcegen/bytecode/ByteCodeWriterTest.java
  sourcegen-generator-java/src/main/java/io/micronaut/sourcegen/JavaPoetSourceGenerator.java
  sourcegen-generator-java/src/test/java/io/micronaut/sourcegen/javapoet/write/ExpressionWriteTest.java
  sourcegen-generator-kotlin/src/main/kotlin/io/micronaut/sourcegen/KotlinPoetSourceGenerator.kt
  sourcegen-generator/src/main/java/io/micronaut/sourcegen/generator/visitors/ObjectAnnotationVisitor.java
  sourcegen-model/src/main/java/io/micronaut/sourcegen/model/ExpressionDef.java
  sourcegen-model/src/main/java/io/micronaut/sourcegen/model/JavaIdioms.java
Labels: type: improvement

#229 Sonatype Scan Gradle Plugin
  .github/workflows/central-sync.yml
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release.yml
  build-logic/build.gradle.kts
  build-logic/src/main/groovy/io.micronaut.build.internal.sourcegen-module.gradle
  gradle/libs.versions.toml
Labels: relates-to: build

#230 [sourcegen] Update common files for branch 1.6.x
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: relates-to: build
