Repository micronaut-projects/micronaut-sourcegen, pull requests merged in 2025-04, with the labels that each got.

#284 Support using builder/wither from other processors
  sourcegen-bytecode-writer/src/main/java/io/micronaut/sourcegen/bytecode/EnumGenUtils.java
  sourcegen-generator/src/main/java/io/micronaut/sourcegen/generator/visitors/BuilderAnnotationVisitor.java
  sourcegen-generator/src/main/java/io/micronaut/sourcegen/generator/visitors/BuilderGenerator.java
  sourcegen-generator/src/main/java/io/micronaut/sourcegen/generator/visitors/SuperBuilderAnnotationVisitor.java
  sourcegen-generator/src/main/java/io/micronaut/sourcegen/generator/visitors/WitherAnnotationVisitor.java
  sourcegen-generator/src/main/java/io/micronaut/sourcegen/generator/visitors/WitherGenerator.java
  sourcegen-generator/src/test/groovy/io/micronaut/sourcegen/generator/visitors/IncludeBuilderInSourceGenSpec.groovy
  sourcegen-generator/src/test/groovy/io/micronaut/sourcegen/generator/visitors/TestAnn.java
  sourcegen-generator/src/test/groovy/io/micronaut/sourcegen/generator/visitors/TestRecordGenerator.java
  sourcegen-generator/src/test/resources/META-INF/services/io.micronaut.inject.visitor.TypeElementVisitor
  sourcegen-model/src/main/java/io/micronaut/sourcegen/model/RecordDef.java
Labels: type: improvement

#291 Fix problems with the type signature
  gradle.properties
  sourcegen-bytecode-writer/build.gradle.kts
  sourcegen-bytecode-writer/src/main/java/io/micronaut/sourcegen/bytecode/AbstractConditionalWriter.java
  sourcegen-bytecode-writer/src/main/java/io/micronaut/sourcegen/bytecode/SignatureWriterUtils.java
  sourcegen-bytecode-writer/src/main/java/io/micronaut/sourcegen/bytecode/TypeUtils.java
  sourcegen-bytecode-writer/src/main/java/io/micronaut/sourcegen/bytecode/expression/InvokeInstanceMethodExpressionWriter.java
  sourcegen-bytecode-writer/src/test/groovy/io/micronaut/sourcegen/bytecode/ByteCodeSpec.groovy
  sourcegen-bytecode-writer/src/test/groovy/io/micronaut/sourcegen/bytecode/groovy/IntroductionGenericTypesSpec.groovy
  sourcegen-bytecode-writer/src/test/groovy/io/micronaut/sourcegen/bytecode/groovy/MyPrecompiledInterface.groovy
  sourcegen-bytecode-writer/src/test/groovy/io/micronaut/sourcegen/bytecode/groovy/Person.groovy
  sourcegen-bytecode-writer/src/test/groovy/io/micronaut/sourcegen/bytecode/groovy/Stub.groovy
  sourcegen-bytecode-writer/src/test/groovy/io/micronaut/sourcegen/bytecode/groovy/StubIntroducer.groovy
  sourcegen-bytecode-writer/src/test/java/io/micronaut/sourcegen/bytecode/ByteCodeWriterTest.java
  sourcegen-bytecode-writer/src/test/java/io/micronaut/sourcegen/bytecode/SignatureWriterUtilsTest.java
  sourcegen-generator-java/src/main/java/io/micronaut/sourcegen/JavaPoetSourceGenerator.java
  sourcegen-generator-java/src/test/java/io/micronaut/sourcegen/javapoet/write/TypeDefTest.java
  sourcegen-generator-kotlin/src/main/kotlin/io/micronaut/sourcegen/KotlinPoetSourceGenerator.kt
  sourcegen-generator/src/main/java/io/micronaut/sourcegen/generator/visitors/DelegateAnnotationVisitor.java
  sourcegen-generator/src/main/java/io/micronaut/sourcegen/generator/visitors/WitherAnnotationVisitor.java
  sourcegen-model/src/main/java/io/micronaut/sourcegen/model/ClassTypeDef.java
  sourcegen-model/src/main/java/io/micronaut/sourcegen/model/ExpressionDef.java
  sourcegen-model/src/main/java/io/micronaut/sourcegen/model/LambdaDef.java
  sourcegen-model/src/main/java/io/micronaut/sourcegen/model/MethodDef.java
  sourcegen-model/src/main/java/io/micronaut/sourcegen/model/TypeDef.java
  test-suite-bytecode/src/test/java/io/micronaut/sourcegen/example/IfsPredicateTest.java
  test-suite-custom-generators/src/main/java/io/micronaut/sourcegen/custom/visitor/GenerateIfsPredicateVisitor.java
  test-suite-custom-generators/src/main/java/io/micronaut/sourcegen/custom/visitor/GenerateLambdaVisitor.java
  test-suite-java/src/test/java/io/micronaut/sourcegen/example/IfsPredicateTest.java
  test-suite-kotlin/build.gradle.kts
  test-suite-kotlin/src/test/kotlin/io/micronaut/sourcegen/example/IfsPredicateTest.kt
Labels: bug

#296 Use resolved generic placeholder value if available
  sourcegen-bytecode-writer/src/test/groovy/io/micronaut/sourcegen/bytecode/ByteCodeSpec.groovy
  sourcegen-model/src/main/java/io/micronaut/sourcegen/model/MethodDef.java
  sourcegen-model/src/main/java/io/micronaut/sourcegen/model/TypeDef.java
  test-suite-bytecode/src/test/java/io/micronaut/sourcegen/example/IfsPredicateTest.java
  test-suite-custom-generators/src/main/java/io/micronaut/sourcegen/custom/visitor/GenerateIfsPredicateVisitor.java
Labels: type: bug
